prueba_expediente:
    resource: "@PruebaBundle/Resources/config/routing/expediente.yml"
    prefix:   /expediente

prueba_contactar:
    path: /contactar/{lugar}
    defaults: { _controller: PruebaBundle:Default:contactar,lugar:'SantaFe' }
prueba_homepage:
    path:     /
    defaults: { _controller: PruebaBundle:Default:index }

prueba_nombre:
    path:     /nombre/{nPila}
    defaults: { _controller: PruebaBundle:Default:nombre }
prueba_nombreR:
    path:     /nombreR/{nPila}
    defaults: { _controller: PruebaBundle:Default:nombreR }
#este es para el caso en el que no escriba un nombre, que lo mande al error
prueba_nombre2:
    path:     /nombre
    defaults: { _controller: PruebaBundle:Default:nombreSinParam }

#trae todos las empresas de los servicios contratados, que estan en la bd
all_servicios:
    path:     /all_servicios
    defaults: { _controller: PruebaBundle:Servicio:all }

#Prueba del twig con for
prueba_tag_for:
    path:     /nombres
    defaults: { _controller: PruebaBundle:Default:nombres }

crear_servicios:
    path:     /servicios/crear
    defaults: { _controller: PruebaBundle:Servicio:crearServicio }

buscar_servicio:
    path:     /servicios/buscar/{id}
    defaults: { _controller: PruebaBundle:Servicio:buscarServicio,id:1 }
    methods: [GET]

#API
api_servicio:
    path: /api/servicio/{compania}
    defaults: { _controller: PruebaBundle:Api:servicio,compania:'Sin Definir' }
    methods: [GET]
#API2
api_servicio_crear:
    path: /api/servicio
    defaults: { _controller: PruebaBundle:Api:crearServicio}
    methods: [POST]


buscarPorCompania_servicio:
    path:     /serviciosPorCompania/{compania}
    defaults: { _controller: PruebaBundle:Servicio:buscarServicioPorCompania,compania:'TELECOM' }

actualizar_servicio:
    path:     /actualizarServicio/{id}/{compania}
    defaults: { _controller: PruebaBundle:Servicio:actualizarServicio }

nuevo_servicios:
    path:     /servicios/nuevo
    defaults: { _controller: PruebaBundle:Servicio:nuevo }

nuevo_servicios_exp:
    path:     /servicios/nuevoExp
    defaults: { _controller: PruebaBundle:Servicio:nuevoExp }

usuario_registro:
    path:     /register
    defaults: { _controller: PruebaBundle:Default:register }

login:
    path:     /usuarios/login
    defaults: { _controller: PruebaBundle:Default:login }

usuarios:
    path:     /usuarios
    defaults: { _controller: PruebaBundle:Default:usuarios }

servicio_index:
    path:     /servicio
    defaults: { _controller: PruebaBundle:servicio:index }
    methods:  GET

servicio_show:
    path:     /{id}/show
    defaults: { _controller: PruebaBundle:servicio:show }
    methods:  GET

servicio_new:
    path:     /nuevo
    defaults: { _controller: PruebaBundle:servicio:new }
    methods:  [GET, POST]

servicio_edit:
    path:     /{id}/edit
    defaults: { _controller: PruebaBundle:servicio:edit }
    methods:  [GET, POST]

servicio_delete:
    path:     /{id}/delete
    defaults: { _controller: PruebaBundle:servicio:delete }
    methods:  DELETE