admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin


prueba:
    resource: "@PruebaBundle/Resources/config/routing.yml"
    prefix:   /

expediente:

    resource: "@PruebaBundle/Resources/config/routing/expediente.yml"
    prefix:   /expediente


factura:
    resource: "@PruebaBundle/Resources/config/routing/factura.yml"
    prefix:   /factura

app:
    resource: '@AppBundle/Controller/'
    type: annotation

welcome:
    path:     /inicio
    defaults: { _controller: AppBundle/Welcome/index }

logout:
    path: /prueba/usuarios/logout
