<?php

namespace PruebaBundle\Repository;

/**
 * ExpedienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpedienteRepository extends \Doctrine\ORM\EntityRepository
{
}
